# Generated by Django 4.0.5 on 2022-07-02 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('id_user', models.IntegerField()),
                ('user_image', models.ImageField(upload_to='user_images')),
                ('user_bio', models.TextField(blank=True)),
                ('user_location', django_countries.fields.CountryField(max_length=2)),
                ('years_of_experience', models.CharField(max_length=12)),
                ('resume_upload', models.FileField(upload_to='users_resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
