# Generated by Django 4.0.5 on 2022-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quikapp', '0003_userprofile_portfolio_link_userprofile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='talent',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(default='What are your skills?'),
        ),
    ]
